# Generated by Django 6.0.1 on 2026-01-29 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("insurance_pending", "Insurance Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("insurance", "Insurance"),
                            ("online", "Online"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("invoice_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "bills",
                "ordering": ["-invoice_date"],
            },
        ),
    ]
