# Generated by Django 5.1.5 on 2026-02-08 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_id"),
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bill",
            name="bills_payment_3c738d_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="bills_stripe__856b14_idx",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="error_message",
            new_name="admin_notes",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="insurance_claim_id",
            new_name="bank_name",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="balance_due",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="insurance_claim_id",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="patient_responsibility",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="stripe_charge_id",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="stripe_payment_intent_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_insurance_payment",
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="routing_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="wallet_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="wallet_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("digital_wallet", "Digital Wallet"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("patient", "stripe_payment_method_id")},
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["invoice_status"], name="bills_invoice_3a507d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["stripe_invoice_id"], name="bills_stripe__2026b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["created_at"], name="bills_created_15ebce_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="payments_payment_ee488d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
    ]
