# Generated by Django 5.1.5 on 2026-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("logger", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                ("module", models.CharField(blank=True, max_length=255, null=True)),
                ("function", models.CharField(blank=True, max_length=255, null=True)),
                ("line", models.IntegerField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=500, null=True)),
                ("exception", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
