# Generated by Django 5.1.5 on 2026-02-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.TextField()),
                ("prescription", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("sensitive", "Sensitive"),
                            ("highly_sensitive", "Highly Sensitive"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
