# Generated by Django 6.0.1 on 2026-01-29 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specialists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability",
                to="specialists.specialist",
            ),
        ),
        migrations.AddField(
            model_name="specialistservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialists",
                to="specialists.service",
            ),
        ),
        migrations.AddField(
            model_name="specialistservice",
            name="specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="specialists.specialist",
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["specialist", "day_of_week", "start_time"],
                name="availabilit_special_a865f8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="specialistservice",
            unique_together={("specialist", "service")},
        ),
    ]
