# Generated by Django 5.1.5 on 2026-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
