# Generated by Django 5.1.5 on 2026-02-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
